image: node:12

variables:
    CARGO_HOME: "$CI_PROJECT_DIR/.cargo"
    RUSTUP_HOME: "$CI_PROJECT_DIR/.rustup"

cache:
  paths:
    - tests/node_modules/
    - tests/nearcore/
    - .cargo/
    - tests/out/

stages:
  - install
  - install-tests
  - build
  - test

install_dependencies:
  stage: install
  script:
    - yarn

install_test_dependencies:
  stage: install-tests
  script:
    - cd tests && yarn && yarn remove near-runtime-ts && yarn add ../

build_test_wasm:
  stage: build
  script:
    - cd tests && yarn build

build_near_vm_runner_standalone:
  stage: build
  script:
    - export PATH="$PATH:$CARGO_HOME/bin"
    - cd tests && ./build-near-vm-runner-standalone.sh

run_aspect_tests:
  stage: test
  script:
    - cd tests && yarn asp

run_assembly_test:
  stage: test
  script:
    - cd tests && ./test.sh
