image: node:12

variables:
    CARGO_HOME: "$CI_PROJECT_DIR/.cargo/"

cache:
  paths:
    - node_modules/
    - tests/node_modules/
    - tests/nearcore/
    - .cargo/
    - tests/out/

stages:
  - install
  - build
  - test

install_dependencies:
  stage: install
  script:
    - yarn && yarn add nearprotocol/assemblyscript

install_test_dependencies:
  stage: install
  script:
    - cd tests && yarn

build_test_wasm:
  stage: build
  script:
    - cd tests && yarn build

build_near_vm_runner_standalone:
  stage: build
  script:
    - cd tests && ./build-near-vm-runner-standalone.sh

run_aspect_tests:
  stage: test
  script:
    - cd tests && yarn test

run_assembly_test:
  stage: test
  script:
    - cd tests && ./test.sh
